### ISSUE TITLE
Error during make setup

### ISSUE THREAD

**Issue by jaimeiniesta** [elixirschool/school_house#78]
I was setting up the repo and run into this when running `make setup`:

```
== Compilation error in file lib/school_house/lessons.ex ==
** (ArgumentError) argument error
    :erlang.binary_to_integer("Elixir School")
    (elixir 1.12.0) lib/enum.ex:1553: Enum."-map/2-lists^map/1-0-"/2
    lib/school_house/content/lesson.ex:77: SchoolHouse.Content.Lesson.parse_version/1
    lib/school_house/content/lesson.ex:36: SchoolHouse.Content.Lesson.build/3
    (nimble_publisher 0.1.1) lib/nimble_publisher.ex:44: anonymous fn/3 in NimblePublisher.__extract__/2
    (elixir 1.12.0) lib/enum.ex:2356: Enum."-reduce/3-lists^foldl/2-0-"/3
    (nimble_publisher 0.1.1) lib/nimble_publisher.ex:41: NimblePublisher.__extract__/2
    lib/school_house/lessons.ex:31: (module)
    lib/school_house/lessons.ex:31: anonymous fn/2 in :elixir_compiler_43.__MODULE__/1
    (elixir 1.12.0) lib/enum.ex:2356: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/school_house/lessons.ex:11: (module)
make: *** [setup] Error 1
```

**Comment by doomspork** [comment]
@jaimeiniesta I or @kinson will take a peek today. I'm in meetings for a bit at the moment though.

**Comment by jaimeiniesta** [comment]
It looks like a false alarm, I removed the directory and cloned the repo again, everything works fine this time!

I guess I had some old files lying around...
